# Config file for `air` (https://github.com/cosmtrek/air)

[build]
  bin = "notes"
  cmd = "go build -o ./notes"
  full_bin = "./notes"
  watch_dir = "."
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "node_modules", "tmp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = true
  force_polling = false
  poll_interval = 500
  stop_on_error = true
  delay = 0
  keep_log = true
  log_file = ""
  graceful = true
  restart_on_write_error = true
  args_bin = []
  args_bef = []
  args_aft = []

[log]
  colored = true
  timestamp = true

[server]
  root = "."
  port = 8080
  address = "0.0.0.0"
  host = "localhost"
  read_timeout = 10
  write_timeout = 1
